language: node_js

node_js:
  - "8.9.4"

install:
  - yarn install

env:
  global:
    - PDAPI=https://api.pagerduty.com
    - PD_VSTS_VERSION=0.1.$TRAVIS_BUILD_NUMBER
    - PD_VSTS_HOOK_URL=https://app.pagerduty.com/vsts/incidents/update?api_key\={{{apikey}}}

matrix:
  include:
    - env: PD_VSTS_PUBLISHER=Denis_Release PD_GALLERY_FLAGS= RELEASE=false
    - env: PD_VSTS_PUBLISHER=Denis_Staging PD_GALLERY_FLAGS=''"Preview", "Public"' RELEASE=true

script:
  - bin/build.sh
  - if [[ "$RELEASE" = 'true' && "$TRAVIS_PULL_REQUEST" == 'false' ]]; then bin/deploy.sh; fi;

branches:
  only:
    - master


# addons:
#   artifacts:
#     paths:
#       - $PD_VSTS_PUBLISHER.pagerduty-latest.vsix