language: node_js

node_js:
  - "8.9.4"

install:
  - yarn install

script:
  - bin/build.sh

branches:
  only:
    - master
    - testrep

addons:
  artifacts:
    paths:
      - $PD_VSTS_PUBLISHER.pagerduty-latest.vsix